"""
point.builders.collections
~~~~~~~~~~~~~~~~~~~~~~~~~~

Collection generation system.

Responsibilities
----------------

Generate collection resources from
Point documents.

Features
--------

- collection extraction
- collection validation
- markdown generation
- json generation

Pipeline
--------

Documents
     ↓

Parser
     ↓

AST
     ↓

CollectionBuilder
     ↓

collections.json
collections/index.md

Overview
--------

Collections provide structured relationships
between Point documents.

A collection may represent:

- Learning Paths
- Documentation Series
- RFC Series
- Standards Groups
- Blog Series
- Audit Collections
- Roadmap Collections
"""

from __future__ import annotations

import json
from dataclasses import (
    asdict,
    dataclass,
)
from pathlib import Path

from point.ast.nodes import (
    Collection as CollectionNode,
    Document,
)


@dataclass(slots=True)
class CollectionEntry:
    """
    Collection definition.

    Attributes
    ----------

    title:
        Collection name.

    documents:
        Ordered document sequence.
    """

    title: str

    documents: list[str]


class CollectionBuilder:
    """
    Build collection resources.

    Outputs
    -------

    collections.json

    collections/index.md
    """

    def build(
        self,
        documents: list[Document],
        output_dir: Path,
    ) -> None:
        """
        Build collection resources.
        """

        collections = self.extract_collections(
            documents,
        )

        output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.write_json(
            collections,
            output_dir / "collections.json",
        )

        self.write_markdown(
            collections,
            output_dir / "index.md",
        )

    def extract_collections(
        self,
        documents: list[Document],
    ) -> list[CollectionEntry]:
        """
        Extract collections from documents.
        """

        collections: list[CollectionEntry] = []

        seen: set[str] = set()

        for document in documents:
            for node in document.children:
                if not isinstance(
                    node,
                    CollectionNode,
                ):
                    continue

                if node.title in seen:
                    continue

                seen.add(
                    node.title,
                )

                collections.append(
                    CollectionEntry(
                        title=node.title,
                        documents=node.documents,
                    )
                )

        #
        # Default collection
        #

        if not collections:
            collections.append(
                CollectionEntry(
                    title="Recommended Order",
                    documents=[
                        document.title
                        for document in documents
                    ],
                )
            )

        collections.sort(
            key=lambda collection:
            collection.title.lower(),
        )

        return collections

    def write_json(
        self,
        collections: list[CollectionEntry],
        output_file: Path,
    ) -> None:
        """
        Write collections JSON.
        """

        data = [
            asdict(collection)
            for collection in collections
        ]

        output_file.write_text(
            json.dumps(
                data,
                indent=4,
            ),
            encoding="utf-8",
        )

    def write_markdown(
        self,
        collections: list[CollectionEntry],
        output_file: Path,
    ) -> None:
        """
        Write collections page.
        """

        lines = [
            "# Collections",
            "",
            (
                "Structured document collections "
                "generated by Point."
            ),
            "",
        ]

        for collection in collections:
            lines.extend(
                [
                    f"## {collection.title}",
                    "",
                ]
            )

            for index, document in enumerate(
                collection.documents,
                start=1,
            ):
                lines.append(
                    f"{index}. {document}"
                )

            lines.append("")

        output_file.write_text(
            "\n".join(lines),
            encoding="utf-8",
        )
