"""
point.vitepress.generator
~~~~~~~~~~~~~~~~~~~~~~~~~

VitePress generation utilities.

Responsibilities
----------------

Generate VitePress configuration and supporting
site files for Point projects.

Features
--------

- index generation
- sidebar generation
- theme generation
- vitepress config generation
- glossary integration
- collections integration
- knowledge graph integration
- GitHub Pages support
- custom styling support

Pipeline
--------

Point Project
      ↓

Generated Markdown
      ↓

VitePress Generator
      ↓

.vitepress/
      ↓

Static Documentation Site
"""

from pathlib import Path

from point.project.manager import (
    ProjectManager,
)
from point.project.scanner import (
    scan_documents,
)


def generate_index(
    docs_dir: Path,
) -> None:
    """
    Generate default home page.
    """

    content = """\
# Welcome

Built with Point.

## Explore

Use the sidebar to navigate documents and generated resources.

## Resources

Point automatically generates:

- Glossary
- Collections
- Knowledge Graph

## Features

- Structured documents
- Concepts and definitions
- Reusable content
- Collections
- Knowledge relationships

## Getting Started

1. Open a document
2. Explore the glossary
3. Browse collections
4. Discover connected concepts
"""

    (docs_dir / "index.md").write_text(
        content,
        encoding="utf-8",
    )


def generate_sidebar(
    project: ProjectManager,
) -> str:
    """
    Generate sidebar configuration.
    """

    documents = scan_documents(
        project.documents_dir,
    )

    groups: dict[str, list[str]] = {}

    section_order: list[str] = []

    for document in documents:
        relative = document.relative_to(
            project.documents_dir,
        )

        relative = relative.with_suffix(
            ".md",
        )

        if len(relative.parts) > 1:
            section = (
                relative.parts[0]
                .replace("-", " ")
                .replace("_", " ")
                .title()
            )

        else:
            section = "Documents"

        if document.stem == "welcome":
            title = "Welcome"
            link = "/"

        else:
            title = (
                document.stem
                .replace("-", " ")
                .replace("_", " ")
                .title()
            )

            link = "/" + str(
                relative.with_suffix(""),
            ).replace(
                "\\",
                "/",
            )

        if section not in groups:
            groups[section] = []

            section_order.append(
                section,
            )

        groups[section].append(
            f"""{{
text: "{title}",
link: "{link}"
}}"""
        )

    sidebar_sections: list[str] = []

    for section in section_order:
        items = groups[section]

        sidebar_sections.append(
            f"""{{
text: "{section}",
items: [
{",".join(items)}
]
}}"""
        )

    return f"""
[
{",".join(sidebar_sections)}
]
"""


def generate_theme(
    docs_dir: Path,
) -> None:
    """
    Generate Point VitePress theme.
    """

    theme_dir = (
        docs_dir
        / ".vitepress"
        / "theme"
    )

    theme_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    (
        theme_dir / "custom.css"
    ).write_text(
        """
:root {

    --vp-c-brand-1: #9d00ff;
    --vp-c-brand-2: #b433ff;
    --vp-c-brand-3: #cb66ff;

    --vp-c-brand-soft:
        rgba(157, 0, 255, 0.15);
}

.point-definition,
.point-concept,
.point-theorem {

    margin: 1rem 0;
}

.point-note,
.point-tip,
.point-warning {

    margin: 1rem 0;
}

.point-document {

    margin: 1rem 0;
}

.point-collection {

    margin: 1rem 0;
}
""".strip()
        + "\n",
        encoding="utf-8",
    )

    (
        theme_dir / "index.ts"
    ).write_text(
        """
import DefaultTheme
from "vitepress/theme"

import "./custom.css"

export default {
  extends: DefaultTheme,
}
""".strip()
        + "\n",
        encoding="utf-8",
    )


def generate_config(
    title: str,
    docs_dir: Path,
    base: str = "/",
) -> None:
    """
    Generate VitePress configuration.

    Parameters
    ----------
    title:
        Site title.

    docs_dir:
        Documentation directory.

    base:
        Deployment base path.
    """

    vitepress_dir = (
        docs_dir
        / ".vitepress"
    )

    vitepress_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    project = ProjectManager()

    sidebar = generate_sidebar(
        project,
    )

    content = f"""\
import {{ defineConfig }}
from "vitepress"

export default defineConfig({{

title: "{title}",

description:
"Generated by Point",

base: "{base}",

cleanUrls: true,

head: [
[
"meta",
{{
name: "generator",
content: "Point"
}}
]
],

themeConfig: {{

nav: [

{{
text: "Home",
link: "/"
}},

{{
text: "Glossary",
link: "/glossary/"
}},

{{
text: "Collections",
link: "/collections/"
}},

{{
text: "Graph",
link: "/graph/"
}},

],

sidebar:
{sidebar}

}}

}})
"""

    (
        vitepress_dir
        / "config.mts"
    ).write_text(
        content,
        encoding="utf-8",
    )

    generate_theme(
        docs_dir,
    )
